### ISSUE TITLE
Travis CI build matrix

### ISSUE THREAD

**Issue by larsbrinkhoff** [forthy42/gforth#2]
If you also like to build on OS X, see this: https://docs.travis-ci.com/user/multi-os/ 
(you may have to ask support@github.com to enable this for your repo)

And you can set environment variables to different values if you want to build with different configurations.

For example, I build my Forth using Linux and OS X, `gcc -m32` and `gcc -m64`, and C and x86 targets.  That would be eight build jobs, but x86 is not supported for OS X yet, so I exclude those two:

```
os:
  - linux
  - osx
env:
  - TARGET=c M32=
  - TARGET=c M32=-m32
  - TARGET=x86 M32=
  - TARGET=x86 M32=-m32
matrix:
  exclude:
    - os: osx
      env: TARGET=x86 M32=
    - os: osx
      env: TARGET=x86 M32=-m32
```
